<?php

$namespaces = array('error','success','info','default');
foreach($namespaces as $namespace) {
    $flashmessages = $this->flashmessenger()->render($namespace);
    if(!empty($flashmessages)) {
        $classe = $namespace=='error'?'danger':$namespace;
        echo "<div data-alert='alert' class='alert alert-$classe'>";
        echo "<button class='close' data-dismiss='alert'>&times;</button>";
        echo $flashmessages;
        echo "</div>";
    }
}

?>
<table class="table">
<?php

foreach ($this->utenti as $utente) {
    echo "<tr>";
    echo "<td>".$utente->getName()."</td>";
    // echo "<td><a href='/user/account/delete?id=".$utente->getId()."' class='btn btn-default'>Elimina</a>";
    echo "<td><a href='".$this->url('user/account',array('action'=>'delete', 'id'=>$utente->getId()))."' class='btn btn-default'>Elimina</a>";
    echo "<td><a href='".$this->url('user/account',array('action'=>'edit', 'id'=>$utente->getId()))."' class='btn btn-default'>Modifica</a>";

    echo "</tr>";
}

?>
</table>